color: null
description: null
fieldLayouts:
  49226d0e-cd0c-4473-8d35-6172da536ceb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-03T13:37:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0971765c-419e-4268-b0c9-bf8a2ff0d2b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-03T13:37:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ff8f529f-79cf-4f8b-af51-dc2679bea708 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e07e0e8-1e65-40e4-bb38-2d7783d84401
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-03T13:37:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fbb0a651-fb1f-4832-b5ae-8cdde41d9030 # Blok kleur
            handle: null
            includeInCards: false
            instructions: null
            label: Achtergrondkleur
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81692d83-1499-4205-a2cf-76f660fe9032
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 073a9d65-28fb-478f-b399-b3c725f9a2c5
        userCondition: null
handle: contentblockKader
hasTitleField: false
icon: indent
name: 'Blok Kader'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
