color: null
description: null
fieldLayouts:
  c9cc4b2a-96b0-4c36-a626-11fda4ccc93e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-18T08:13:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Paginatitel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a5f5afa8-1240-4a83-be4a-e467c3ab4335
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-11T10:47:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 83db36ef-e67b-4f25-971a-ebc7ec0dea3e # Plain Text
            handle: payoff
            includeInCards: false
            instructions: null
            label: Payoff
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec22e41f-31ac-4959-ab7e-50784b54eb9d
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Afbeelding header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41f13869-f83a-44be-80db-021f477823dd
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-10-11T09:29:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fbb0a651-fb1f-4832-b5ae-8cdde41d9030 # Blok kleur
            handle: pageTheme
            includeInCards: false
            instructions: null
            label: 'Pagina kleur'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53601152-1d79-45ca-b462-f1c13db17ca7
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-18T08:31:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: intro
            includeInCards: false
            instructions: null
            label: Introductie
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89acb030-f509-4c9f-adeb-93b7c4f84eb8
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b61a538-af28-46cf-b884-bb22dc1821ca # SEO Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40db4703-8e6e-4e12-98e6-de82de4cdf9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67cef168-b53a-4bea-a071-f71da098360a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bedcd512-47d2-4bf6-b77b-fa82d8d107cf # Content blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07ee2dab-fb14-4048-9113-5dd99645c487
            userCondition: null
            warning: null
            width: 100
        name: 'Content blokken'
        uid: f8ca6420-855b-4f09-888f-121d23ddd629
        userCondition: null
handle: cursus
hasTitleField: true
icon: graduation-cap
name: Cursus
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
