color: null
description: 'Subpagina van een cursus'
fieldLayouts:
  03e36882-fc0d-411b-ab39-e3f2c58444e7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-18T08:13:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Paginatitel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b992c10d-fe4f-4b7b-b90d-066012d55af3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-11T10:47:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 83db36ef-e67b-4f25-971a-ebc7ec0dea3e # Plain Text
            handle: payoff
            includeInCards: false
            instructions: null
            label: Payoff
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 918ba08b-6912-4115-8393-ff7ea8f94e47
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-18T08:31:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: intro
            includeInCards: false
            instructions: null
            label: Introductie
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 368eaf8e-41c7-49ac-bed9-b6bfbca01c26
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-11-04T13:25:36+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5c1eb727-5b5d-41f2-9924-ccb0100aad07
            userCondition: null
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Afbeelding header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9182373-61f2-433d-bf13-b225290e4192
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-10-11T09:29:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fbb0a651-fb1f-4832-b5ae-8cdde41d9030 # Blok kleur
            handle: pageTheme
            includeInCards: false
            instructions: null
            label: 'Pagina kleur'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce786f3c-cd01-4884-a400-fad423e4f8c3
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b61a538-af28-46cf-b884-bb22dc1821ca # SEO Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58bd752a-9fea-4244-b368-244a38b04d12
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ef0961a-39d8-4c19-acad-3da150027f90
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bedcd512-47d2-4bf6-b77b-fa82d8d107cf # Content blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0813e4ee-263a-4fd2-bca1-4ba943cfa39f
            userCondition: null
            warning: null
            width: 100
        name: 'Content blokken'
        uid: 17e4ded7-3358-4184-bd0b-4b1a238808b3
        userCondition: null
handle: cursusDetail
hasTitleField: true
icon: graduation-cap
name: 'Cursus Detailpagina'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
