color: null
description: null
fieldLayouts:
  a597a301-edef-47f8-b819-2e63225164c3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-18T08:13:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Paginatitel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 886f0b12-0e25-4312-ae59-d550e8cb609d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-18T08:31:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: intro
            includeInCards: false
            instructions: null
            label: Introductie
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b830717c-48f4-4b25-92e5-a3eac6274008
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: null
            includeInCards: false
            instructions: null
            label: Afbeelding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20d1794a-f2cc-4e30-858f-6d90a9d58186
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-10-15T16:26:01+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
                  layoutElementUid: 20d1794a-f2cc-4e30-858f-6d90a9d58186
                  operator: notempty
                  uid: 3f99e53f-f923-4c64-a7b8-4989bf1f5669
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f30926c9-bf98-4136-a4d3-fe5d5181a595 # Toon bijschrift
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fa6a760-2339-4422-be6c-e793c37c6a82
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b61a538-af28-46cf-b884-bb22dc1821ca # SEO Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e8de2bb-8632-401f-9c74-2d70726e31c0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1a9d26c-ba8e-4680-95d1-e38d0c6f57df
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-18T08:22:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bedcd512-47d2-4bf6-b77b-fa82d8d107cf # Content blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed769a8b-44ff-4dcc-8795-aca362fbe449
            userCondition: null
            warning: null
            width: 100
        name: 'Content blokken'
        uid: 607d2f56-c35d-4b53-93eb-57bbf58b6c78
        userCondition: null
handle: overOnsDetail
hasTitleField: true
icon: square-info
name: 'Over ons - Detailpagina'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
