dateModified: 1762178921
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Channels
      key: 'heading:f76c1f43-95f7-4b23-b619-4c8a3de13913'
      type: heading
    -
      key: 'section:793dad19-c178-4275-b20d-08a0d2653b03' # Actueel
      type: native
    -
      key: 'section:19eb76be-2b91-4238-b8ff-3654257a1783' # Agenda
      type: native
    -
      key: 'section:060b8f3c-e6c6-421a-823a-5f01fc8641b1' # Pagina's
      type: native
    -
      key: 'section:3c79070d-f645-4fc2-bfd2-c0a46838c559' # Projecten
      type: native
    -
      heading: Structures
      key: 'heading:5057f892-f746-428b-8a64-3134fbee48f0'
      type: heading
    -
      key: 'section:3c8b0879-8c6e-427c-aa4c-483780f2b33f' # Over ons
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:d9c53df5-8662-42be-bec2-bb159387f8bd' # Wat we doen
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      key: 'heading:cf25e743-f19a-49cc-9a10-f91731d3d0e5'
      type: heading
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: ''
      key: 'heading:02cb746e-4f69-4a3c-99c3-078e8c4628b8'
      type: heading
    -
      key: 'section:f28691f2-ad80-4fda-89ab-fc062f4c1e16' # Overzicht blokken
      type: native
email:
  fromEmail: peter@peterboorsma.nl
  fromName: Biosintrum
  transportType: craft\mail\transportadapters\Sendmail
fs:
  localStorage:
    hasUrls: true
    name: 'Local Storage'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: $ASSETS_URL
meta:
  __names__:
    1ca63ceb-4a9f-404b-9924-fbfc2ecc808a: 'Blok Embed' # Blok Embed
    1cd78da4-b08a-49e9-80a6-9aaa808ecb8a: Tarieven # Tarieven
    1dcb2d06-322f-4f10-bc76-728c618a57a6: Homepage # Homepage
    1f01644c-76d1-44e0-b546-bf3bb10dce78: 'Public Schema' # Public Schema
    2bce9a53-eac8-45c0-83b9-3cfbf5e709e7: 'Afbeelding formaat' # Afbeelding formaat
    2dd9ed81-e1a2-4c3d-8200-9c971bc0a514: 'Blok type' # Blok type
    3c8b0879-8c6e-427c-aa4c-483780f2b33f: 'Over ons' # Over ons
    3c79070d-f645-4fc2-bfd2-c0a46838c559: Projecten # Projecten
    4acbf173-f5b9-48c3-8ffb-906f3a57a3ce: Paginas # Paginas
    4dbf591f-220c-49e2-b6ee-63c6a4cf108d: 'Partner list' # Partner list
    4f212a46-d489-4335-ae26-73116a6a1228: 'Assets Embed' # Assets Embed
    5bb3cb31-9529-4f7b-b407-bee0476b98df: Actueel # Actueel
    5d8cb6ad-2d15-4d50-a184-8219793c33d4: Ruimtes # Ruimtes
    6a60fde2-cd48-49ee-aadb-8d8a6bc7a722: 'Button Set' # Button Set
    6bb5c91d-ecfb-4ca7-93ad-9a68ae361e87: Embeds # Embeds
    6d8a5491-1714-4fcd-bb76-6783f345f70e: 'Over ons - Hoofdpagina' # Over ons - Hoofdpagina
    7db4c8c9-64ae-4f55-9955-8ec3059fb9d1: Biosintrum # Biosintrum
    8b61a538-af28-46cf-b884-bb22dc1821ca: 'SEO Content' # SEO Content
    8c4d9ab3-2305-4b12-b68f-3c1cad72d49a: 'Assets Partnerlogo' # Assets Partnerlogo
    9c2b5efe-b549-4e63-a2f3-8c1ee5ea7704: Blok # Blok
    15ccb303-9172-4a05-82fb-a3f2ac94efa1: 'Dagdeel en prijs' # Dagdeel en prijs
    19eb76be-2b91-4238-b8ff-3654257a1783: Agenda # Agenda
    060b8f3c-e6c6-421a-823a-5f01fc8641b1: "Pagina's" # Pagina's
    83db36ef-e67b-4f25-971a-ebc7ec0dea3e: 'Plain Text' # Plain Text
    86b4bc13-5cc4-482a-ba3d-a1200f77f0c5: 'Select Entry' # Select Entry
    87e67b83-5cc3-4d47-8fc8-17066869cf9b: 'Blok Knoppen' # Blok Knoppen
    92f1bb18-bfa6-4a06-8a97-4d082ea82fe6: Projecten # Projecten
    233fda5c-b05d-4f02-99af-20045ba42e31: Prijs # Prijs
    541f273a-fe62-42d9-8ee8-b04fcb32e786: Tarievenlijst # Tarievenlijst
    601fba76-351e-4ee9-b9a9-5b49523baf37: Partnerlink # Partnerlink
    754fbb27-0657-4cc1-a8d5-707b736f92ce: 'Blok Kader' # Blok Kader
    793dad19-c178-4275-b20d-08a0d2653b03: Actueel # Actueel
    884dd8a2-8ede-4a60-af46-769c69dfa8d4: 'Externe URL' # Externe URL
    926b61e9-462a-408c-ad86-aed1b332d5b5: 'Button Group' # Button Group
    979b5ab9-7b2b-411f-a3b1-3e5a3e2deae8: 'Image Position' # Image Position
    1502d8b3-00a7-4e45-aeee-dd35ffe4295d: 'Overzicht blok' # Overzicht blok
    8235d94d-82ef-4fb0-ae36-807b331b730a: 'Assets Image' # Assets Image
    23469c41-a809-450c-82c2-40780afd23a6: Images # Images
    26665a77-50f7-442f-9069-fc3731cfc38d: Simple # Simple
    99308e96-c44c-4639-8d40-4ef316b1e1a1: Datum # Datum
    0448039b-68a3-4865-a28b-24d17f5f6a5c: 'Button Download' # Button Download
    602693e8-e56b-49d6-97cd-b74f05363a84: Homepage # Homepage
    0786903a-5a76-4014-bd83-bd4ea9450867: 'Over ons - Detailpagina' # Over ons - Detailpagina
    885762b5-ddee-4206-9942-0082031777e1: Default # Default
    4865191d-aa39-495d-9ae2-b5f0e62578f1: 'SEO Description' # SEO Description
    5168636d-e73b-40fa-9a36-e1146da0c43d: 'Wat we doen - Hoofdpagina' # Wat we doen - Hoofdpagina
    8840259d-eec9-46fc-8674-0207cf7b629d: Adresgegevens # Adresgegevens
    a66ccb8d-61fd-4360-bf30-2a56894318fa: Partnerlogos # Partnerlogos
    aa77c39f-f098-4ed3-bb08-a460a8d3fce3: 'Over ons - Partners' # Over ons - Partners
    af50c774-c285-4afd-a496-c976e435b15d: 'Leer- en kenniscentrum Bodem' # Leer- en kenniscentrum Bodem
    b043b78c-7bde-4b91-9e47-722b106c9106: Downloads # Downloads
    b378d7b8-6042-489d-b53d-727c66711509: 'Assets Download' # Assets Download
    b64307a7-ec4a-46ea-8836-cf6a7de0c856: 'Blok Afbeelding' # Blok Afbeelding
    bedcd512-47d2-4bf6-b77b-fa82d8d107cf: 'Content blokken' # Content blokken
    c2b2a36e-09ab-4914-af1d-95b82be1e457: Cursus # Cursus
    cc792267-b10b-4acf-ab7c-e920877e89bc: 'Social media' # Social media
    d9c53df5-8662-42be-bec2-bb159387f8bd: 'Wat we doen' # Wat we doen
    d163a572-6de6-4dc1-8c1c-9ebb5a42f8b2: 'Wat we doen - Detailpagina' # Wat we doen - Detailpagina
    dc6bde34-ac1d-4ae5-a643-87784759763f: 'Gekoppelde projecten' # Gekoppelde projecten
    ea332f3c-3ce7-4df7-993d-a59dd5f7464c: 'Wat we doen - Themapagina' # Wat we doen - Themapagina
    f3fbba55-9047-45a2-9bdd-0013a9b83f23: 'Rich Text' # Rich Text
    f8fac004-81f8-4a88-8825-0342279070ee: 'Plain Text Multiline' # Plain Text Multiline
    f28691f2-ad80-4fda-89ab-fc062f4c1e16: 'Overzicht blokken' # Overzicht blokken
    f30926c9-bf98-4136-a4d3-fe5d5181a595: 'Toon bijschrift' # Toon bijschrift
    fb0d368d-2fb7-4027-a060-679959808366: Biosintrum # Biosintrum
    fbb0a651-fb1f-4832-b5ae-8cdde41d9030: 'Blok kleur' # Blok kleur
    ff8f529f-79cf-4f8b-af51-dc2679bea708: 'Button Link' # Button Link
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cloner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Biosintrum
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/Amsterdam
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
