defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 5168636d-e73b-40fa-9a36-e1146da0c43d # Wat we doen - Hoofdpagina
  -
    uid: ea332f3c-3ce7-4df7-993d-a59dd5f7464c # Wat we doen - Themapagina
  -
    uid: d163a572-6de6-4dc1-8c1c-9ebb5a42f8b2 # Wat we doen - Detailpagina
  -
    uid: c2b2a36e-09ab-4914-af1d-95b82be1e457 # Cursus
  -
    uid: a880cdc5-16d6-49d5-bc00-2ad09f3a9a3d # Cursus Detailpagina
  -
    uid: 5d8cb6ad-2d15-4d50-a184-8219793c33d4 # Ruimtes
handle: watWeDoen
maxAuthors: 1
name: 'Wat we doen'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fb0d368d-2fb7-4027-a060-679959808366: # Biosintrum
    enabledByDefault: true
    hasUrls: true
    template: watwedoen/_entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 4
  uid: a7c4387d-ea8d-4ec2-b12c-40cbf9fc95ce
type: structure
